<a href="https://colab.research.google.com/github/Woobin-Seo/Python/blob/master/Ipynb/Q_Table_Update.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import gym

In [0]:
import numpy as np

In [3]:
env = gym.make('FrozenLake8x8-v0') #4x4

/usr/local/lib/python3.6/dist-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)


In [0]:
# !pip install scipy

In [0]:
Q = np.zeros([env.observation_space.n, env.action_space.n])

In [0]:
# Q

In [0]:
lr = 0.8 # learning rate
y = 0.95 # 割引率
num_episodes = 2000
rList = []

In [0]:
for i in range(num_episodes):
  s = env.reset()
  rAll = 0
  d = False
  j = 0
  
  while j < 99:
    j += 1
    a = np.argmax(Q[s,:] + np.random.randn(1, env.action_space.n) * (1.0 / (i + 1)))
    s1, r, d,_ = env.step(a)
    Q[s, a] = Q[s, a] + lr * (r + y * np.max(Q[s1,:]) - Q[s, a])
    rAll += r
    s = s1
    
    if d == True:
      break
  
  rList.append(rAll)

In [0]:
 #rList #1.0はゴールまでたどり着いた場合

In [8]:
print("回数ごとの結果:" + str(sum(rList) / num_episodes))

回数ごとの結果:0.0155


In [9]:
print("最終的なQテーブルの値")

# 左、下、右、上の中で値が高い数値がアクションの最大の報酬値
print(Q)

最終的なQテーブルの値
[[2.21734245e-03 1.67692917e-02 2.22853406e-03 2.19755549e-03]
 [2.31838192e-03 2.33435727e-03 2.36945002e-02 2.23895721e-03]
 [1.64932152e-03 1.66696243e-03 3.82957568e-02 2.49792967e-03]
 [3.00253284e-03 2.92272750e-03 3.96011380e-02 2.01208060e-03]
 [7.34154196e-04 2.27985093e-03 3.08306465e-03 5.80246560e-02]
 [2.95157528e-03 8.44757993e-04 4.82640013e-02 2.18829225e-03]
 [5.36119413e-02 3.12824036e-03 2.19609588e-03 2.27659769e-03]
 [2.24125775e-03 2.13366809e-03 5.80671963e-02 2.98394394e-03]
 [2.38343483e-03 2.18467059e-03 2.14163134e-03 5.94633206e-03]
 [2.10716536e-03 2.08476952e-03 2.45627641e-03 1.52117867e-02]
 [1.03784624e-03 9.72048906e-04 9.94352871e-04 2.78432391e-02]
 [4.62446332e-04 1.42106737e-04 1.75118285e-04 2.78883827e-02]
 [1.30724302e-03 1.70793827e-03 7.60844800e-04 2.74053357e-02]
 [2.01759055e-03 1.50383149e-03 2.37240466e-03 4.93043598e-02]
 [8.38518567e-04 2.16551125e-03 5.33513187e-02 9.69097566e-04]
 [4.14641746e-02 2.11596049e-03 2.10887186e